[tool.mypy]
# --- GLOBAL SETTINGS ---
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
mypy_path = "src"
exclude = "(^sketches/.*|^tests/.*)"

# --- PER-MODULE OVERRIDES ---
# (Keep these at the bottom of the config)

[[tool.mypy.overrides]]
module = "matplotlib.*"
ignore_missing_imports = true

# [[tool.mypy.overrides]]
# module = "pandas.*"
# ignore_missing_imports = true

[tool.ruff]
exclude = ["sketches", "sketches/*", "tests", "tests/*"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
pythonpath = "src"
addopts = "--cov=src --cov-report=term-missing -ra"
